### ISSUE TITLE
Col Offset

### ISSUE THREAD

**Issue by ReganRyanNZ** [rmmfree/shine_css#1]
Hi, love this framework, but how do I offset columns in the grid?

e.g.
.col-4-offset
.col-16

Should make the col-16 centered on the page

**Comment by rmmfree** [comment]
Hello, you can offset columns adding a margin-{number}-left or margin-{number}-right class.
For example:

`<div class="row col-3 lightgreen-bg">Orange</div>`
`<div class="row col-3 lightgreen-bg margin-4-left">Cherry</div>`

The second div has an offset of 4 columns. So, there is an empty space between them of 4 columns.

For creating a 16 column div centered on the screen you can do this:

`<div class="col-16 center">Sample text</div>`

I have created a new example with these margin (offset) classes and I have submitted it right now.

Best Regards.
